import { doSthInSec } from "@/utilities";

export const metadata = {
  title: "Dstore - Home",
  description: "Generated by create next app",
};

export default async function Home() {
  await doSthInSec(1);
  return <div>Home</div>;
}
